### ISSUE TITLE
Documentation Images

### ISSUE THREAD

**Issue by marco-tranzatto** [ethz-asl/mav_rtk_gps#2]
Put here images used in wiki pages

**Comment by marco-tranzatto** [comment]
![piksi_multi_ftdi](https://user-images.githubusercontent.com/5328930/29364649-81fdac56-8294-11e7-8753-931140b9cb3e.png)

**Comment by marco-tranzatto** [comment]
![spectrum](https://user-images.githubusercontent.com/5328930/32789093-39c64746-c95b-11e7-9ad6-cf2d34132c2d.png)

**Comment by marco-tranzatto** [comment]
![throughput](https://user-images.githubusercontent.com/5328930/32789100-3f764434-c95b-11e7-81a7-4b9af1f7bef5.png)

**Comment by marco-tranzatto** [comment]
![throughput_bad](https://user-images.githubusercontent.com/5328930/32789128-4bed2610-c95b-11e7-8347-72e74f127e5f.png)

**Comment by kholtmann** [comment]
[rtk_time_test.pdf](https://github.com/ethz-asl/mav_rtk_gps/files/1517099/rtk_time_test.pdf)

**Comment by kholtmann** [comment]
![rtk_time_tests](https://user-images.githubusercontent.com/15651057/33422109-c4559d8e-d5b4-11e7-91fc-ee0947c731d1.png)
