### ISSUE TITLE
Separate MAV parts from ROS Driver

### ISSUE THREAD

**Issue by marco-tranzatto** [ethz-asl/mav_rtk_gps#49]
Hi people!

As the driver is not being used only by the MAV team I would like at this point to split the init_rovio part and the actual ROS driver in separate repositories (while keeping GIT history). When I asked to create this repo a didn't think about this possibility. I will then take care of updating the Wikis in a more readable way.

@helenol If you're ok with this I'd ask you to create a new repo: ethz_piksi_ros

Thanks,
Marco.

**Comment by helenol** [comment]
I agree and repo created :)

**Comment by alexmillane** [comment]
Thanks for this Marco. Great work.

On Thu, Nov 30, 2017 at 11:26 AM, Helen Oleynikova <notifications@github.com

**Comment by marco-tranzatto** [comment]
addressed in PR #54 

New ROS drivers are now here: [ethz_piksi_ros](https://github.com/ethz-asl/ethz_piksi_ros)
